//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Медицинская_лаборатория
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Services
    {
        public int ID { get; set; }
        public int ID_Employee { get; set; }
        public int ID_Service { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Services Services { get; set; }
    }
}
