//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Медицинская_лаборатория
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Enters
    {
        public int ID { get; set; }
        public Nullable<int> ID_Emloyee { get; set; }
        LaboratoryEntities entity = new LaboratoryEntities();
        public string Employee
        {
            get
            {
                var agent = entity.Employees.First(x => x.ID == ID_Emloyee);
                return $"{agent.Surname} " + $"{agent.Name} " + $"{agent.Patronymic}";
            }
        }
        public Nullable<System.DateTime> Last_Enter_Date { get; set; }
        public Nullable<System.TimeSpan> Last_Enter_Time { get; set; }
        public Nullable<bool> Success { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
