//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Медицинская_лаборатория
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaboratoryEntities : DbContext
    {
        public LaboratoryEntities()
            : base("name=LaboratoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analyzers> Analyzers { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Employees_Services> Employees_Services { get; set; }
        public virtual DbSet<Insurances> Insurances { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Orders_Services> Orders_Services { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Services_Provision> Services_Provision { get; set; }
        public virtual DbSet<Social_Security_Types> Social_Security_Types { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<Enters> Enters { get; set; }
    }
}
