//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Медицинская_лаборатория
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Guid { get; set; }
        public string Email { get; set; }
        public string Social_Sec_Number { get; set; }
        public string Ein { get; set; }
        public int ID_Social_Sec_Type { get; set; }
        public string Phone { get; set; }
        public string Passport_Series { get; set; }
        public string Passport_Number { get; set; }
        public System.DateTime Birth_Date_Timestamp { get; set; }
        public int ID_Country { get; set; }
        public int ID_Insurance { get; set; }
        public string IP_Adress { get; set; }
        public string UA { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Insurances Insurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Social_Security_Types Social_Security_Types { get; set; }
    }
}
