//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Медицинская_лаборатория
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services_Provision
    {
        public int ID { get; set; }
        public int ID_Order_Service { get; set; }
        public double Result { get; set; }
        public System.DateTime Finished_Date_Time { get; set; }
        public bool Accepted { get; set; }
        public int ID_Status { get; set; }
        public int ID_Analyzer { get; set; }
        public int ID_Employee { get; set; }
        public Nullable<double> Execution_Seconds { get; set; }
    
        public virtual Analyzers Analyzers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Orders_Services Orders_Services { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
